<?php


namespace EDC\CommandSchedulerBundle\Command;


use Doctrine\Persistence\ManagerRegistry;
use EDC\CommandSchedulerBundle\Cron\CommandScheduler;
use EDC\CommandSchedulerBundle\Cron\CronCommand;
use EDC\CommandSchedulerBundle\Cron\JobScheduler;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class ScheduleCommand extends Command
{
    protected static $defaultName = 'edc-job-queue:schedule';

    private $registry;

    private $schedulers;

    private $cronCommands;

    /**
     * ScheduleCommand constructor.
     * @param ManagerRegistry $managerRegistry
     * @param iterable $schedulers
     * @param iterable $cronCommands
     */
    public function __construct(ManagerRegistry $managerRegistry, iterable $schedulers, iterable $cronCommands)
    {
        parent::__construct();
        $this->registry = $managerRegistry;
        $this->schedulers = $schedulers;
        $this->cronCommands = $cronCommands;
    }


    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $jobSchedulers = $this->populateJobSchedulers();

        foreach ($jobSchedulers as $jobScheduler) {
            $output->write($jobScheduler->getCommands());
        }

        return 0;
    }

    /**
     * @return JobScheduler[]
     */
    private function populateJobSchedulers()
    {
        $schedulers = [];
        foreach ($this->schedulers as $scheduler) {
            /** @var JobScheduler $scheduler */
            foreach ($scheduler->getCommands() as $name) {
                $schedulers[$name] = $scheduler;
            }
        }

        foreach ($this->cronCommands as $command) {
            /** @var CronCommand $command */
            if (!$command instanceof Command) {
                throw new \RuntimeException('CronCommand should only be used on Symfony commands.');
            }

            $schedulers[$command->getName()] = new CommandScheduler($command->getName(), $command);
        }

        return $schedulers;
    }

}